---
# Lambda School Data Science - Intro to Python  
---
# Assignment 04 - Intro to `numpy`
---



##STOP! BEFORE GOING ANY FURTHER...  


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to "FIRSTNAME_LASTNAME_assign4"  

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and submit. Be sure to do this for ***every*** assignment!

---


## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [3]:
# Import numpy and assign it the standard alias

import numpy as np

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [63]:
# Generate your random numbers
myarray = np.random.randint(101,size=(5,3))
np.random.seed(23)
myarray = np.array(myarray)
# Print out the array

print(myarray)

[[83 40 73]
 [54 31 76]
 [91 39 90]
 [25 51  6]
 [45 12 49]]


### 1.3 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [64]:
# 1. Return the first row:
myarray[0,:]

array([83, 40, 73])

In [65]:
# 2. Return the last column
myarray[:,-1]

array([73, 76, 90,  6, 49])

In [66]:
# 3. Return the third column values from the 4th and 5th rows
myarray[3:5,2]

array([ 6, 49])

In [67]:
# 4. Multiply every value in the array by 2

myarray * 2

array([[166,  80, 146],
       [108,  62, 152],
       [182,  78, 180],
       [ 50, 102,  12],
       [ 90,  24,  98]])

In [68]:
# 5. Divide every value by 3
myarray * (1/3)

array([[27.66666667, 13.33333333, 24.33333333],
       [18.        , 10.33333333, 25.33333333],
       [30.33333333, 13.        , 30.        ],
       [ 8.33333333, 17.        ,  2.        ],
       [15.        ,  4.        , 16.33333333]])

In [69]:
# 6. Increase the values in the first row by 12

myarray[0,:] + 12

array([95, 52, 85])

In [70]:
# 7. Calculate the mean of the first column
np.mean(myarray[:,0])


59.6

In [71]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array

# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)

# remove two smallest values
myarray = myarray[2:]

# calculate the median
np.median(myarray)



51.0

In [81]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
myarray = np.random.randint(101,size=(5,3))
np.random.seed(223)
myarray = np.array(myarray)
np.std(myarray[0:3,:])

24.04060351330537

In [84]:
# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True

condition = myarray[:,1] > 25

# Apply the mask
myarray[condition]

array([[47, 66, 30],
       [39, 26, 76],
       [44, 76, 22]])

In [94]:
# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition2 = myarray[:,:] < 40

# apply the mask
myarray[condition2]

array([24, 33, 27, 36])

### Solution 1.3: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [93]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[57 93 23]
 [13 85 99]
 [16  4 94]
 [94 43 36]
 [75 71 78]]


1. The first row:  [57 93 23]


2. The last column:  [23 99 94 36 78]


3. The 3rd column, 4th & 5th rows:  [36 78]


4. Multiply by 2: 
 [[114 186  46]
 [ 26 170 198]
 [ 32   8 188]
 [188  86  72]
 [150 142 156]]


5. Divide by 3: 
 [[19.         31.          7.66666667]
 [ 4.33333333 28.33333333 33.        ]
 [ 5.33333333  1.33333333 31.33333333]
 [31.33333333 14.33333333 12.        ]
 [25.         23.66666667 26.        ]]


6. Add 12 to the first row: 
 [ 69 105  35]


7. The mean of the 1st column:  51.0


8. The median after removing the 2 smallest values:  75.0


9. The standard deviation is:  21.205054137814745


10. All values in 2nd column > 25: 
 [[24 78 69]
 [42 63 33]
 [55 85 27]
 [46 45 62]
 [76 96 36]]


11. All values < 40: 
 [24 33 27 36]


---
### Submit your assignment notebook! (Make sure you've changed the name to FIRSTNAME_LASTNAME_assign4): 

1.  Click the Share button in the upper-right hand corner of the notebook.
2.  Get the shareable link.
3.  Set condition to: "Anyone with the link can comment."

---